Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Anaconda\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Anaconda\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Anaconda\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Anaconda\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Anaconda\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Anaconda\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Anaconda\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# 1. Read all the files contained in the specified path and save them in a list
path = r"../../_data\sbs\B_RawData\bancos"
file_list = [os.path.join(path, file) for file in os.listdir(path)]
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_15188\2512083849.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m# 1. Read all the files contained in the specified path and save them in a list[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [0mpath[0m [1;33m=[0m [1;34mr"../../_data\sbs\B_RawData\bancos"[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 3[1;33m [0mfile_list[0m [1;33m=[0m [1;33m[[0m[0mos[0m[1;33m.[0m[0mpath[0m[1;33m.[0m[0mjoin[0m[1;33m([0m[0mpath[0m[1;33m,[0m [0mfile[0m[1;33m)[0m [1;32mfor[0m [0mfile[0m [1;32min[0m [0mos[0m[1;33m.[0m[0mlistdir[0m[1;33m([0m[0mpath[0m[1;33m)[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mFileNotFoundError[0m: [WinError 3] El sistema no puede encontrar la ruta especificada: '../../_data\\sbs\\B_RawData\\bancos'
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: '../../_data\\sbs\\B_RawData\\bancos'

