Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Anaconda\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Anaconda\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Anaconda\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Anaconda\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Anaconda\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Anaconda\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Anaconda\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
member1_family1 = FamMember( last_name = "Azabache" , nationality = "Peruvian", name = "Carlos" , age = 26 )
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_13696\561309729.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mmember1_family1[0m [1;33m=[0m [0mFamMember[0m[1;33m([0m [0mlast_name[0m [1;33m=[0m [1;34m"Azabache"[0m [1;33m,[0m [0mnationality[0m [1;33m=[0m [1;34m"Peruvian"[0m[1;33m,[0m [0mname[0m [1;33m=[0m [1;34m"Carlos"[0m [1;33m,[0m [0mage[0m [1;33m=[0m [1;36m26[0m [1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mTypeError[0m: __init__() missing 1 required positional argument: 'school'
TypeError: __init__() missing 1 required positional argument: 'school'

